[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
ignore = "E203, W503"
max-line-length = 88
exclude = "venv/, .git/, __pycache__/"

[tool.mypy]
disallow_untyped_defs = true
disallow_untyped_calls = true
check_untyped_defs = true
strict_optional = true
ignore_missing_imports = true